name: Hopplet
description: $description
version: "$version"

main: au.lupine.hopplet.Hopplet
api-version: "1.21.8"
load: POSTWORLD

authors: [jwkerr]
website: https://lupine.au

contributors:
  - Warriorrr # Helped by improving caching efficiency.

folia-supported: true

libraries:
  - org.spongepowered:configurate-gson:4.2.0

softdepend:
  - Bottlet
  - Towny

permissions:
  hopplet.edit.hopper:
    description: Grants permission to edit the filter of hoppers.
    default: true

  hopplet.edit.hopper_minecart:
    description: Grants permission to edit the filter of hopper minecarts.
    default: true

  hopplet.command.hopplet:
    description: Grants access to the Hopplet command.
    default: true

  hopplet.command.hopplet.edit:
    description: Grants access to the Hopplet edit command.
    default: true

  hopplet.command.hopplet.function:
    description: Grants access to view Hopplet function info.
    default: true

  hopplet.command.hopplet.reload:
    description: Grants access to the Hopplet reload command.
    default: op

commands:
  hopplet:
    description: Command to interface with Hopplet.
    permission: hopplet.command.hopplet